# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
 - group: secrets

# resources:
#   containers:
#   - container: sonar
#     endpoint: dockerHub
#     image: ghcr.io/linuxserver/sonarr

trigger:
- '*'

pool:
  vmImage: ubuntu-latest

jobs:
- deployment: Config
  displayName: config
  environment:
    name: home
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              ls
              docker-compose pull
              PASSWORD=$(PASSWORD) docker-compose config
              PASSWORD=$(PASSWORD) docker-compose restart
              echo 'Hello world'